// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  List all entries in a given directory.
	 *  Returns a sorted vector: directories first, then files, both alphabetically.
	 */
	listDirectory: (path: string) => typedError<FileEntry[], string>(__TAURI_INVOKE("list_directory", { path })),
	/**  Get detailed info about a single file or directory. */
	getFileInfo: (path: string) => typedError<FileInfo, string>(__TAURI_INVOKE("get_file_info", { path })),
	/**
	 *  Create a new directory at the given path.
	 *  The parent directory must already exist.
	 */
	createDirectory: (path: string) => typedError<FileEntry, string>(__TAURI_INVOKE("create_directory", { path })),
	/**  Rename (or move) a file/directory from old_path to new_path. */
	renameItem: (oldPath: string, newPath: string) => typedError<FileEntry, string>(__TAURI_INVOKE("rename_item", { oldPath, newPath })),
	/**
	 *  Delete a file or directory at the given path.
	 *  If permanent is true, deletion is irreversible. If false, we delete permanently for now.
	 *  Directory removal recursively deletes all contents.
	 */
	deleteItem: (path: string) => typedError<null, string>(__TAURI_INVOKE("delete_item", { path })),
	/**  Copy multiple source files/directories to a destination directory. */
	copyItems: (sources: string[], destination: string) => typedError<FileEntry[], string>(__TAURI_INVOKE("copy_items", { sources, destination })),
	/**  Move multiple source files/directories to a destination directory. */
	moveItems: (sources: string[], destination: string) => typedError<FileEntry[], string>(__TAURI_INVOKE("move_items", { sources, destination })),
	/**  Diff the contents of two files line by word level, returning all changes. */
	diffFiles: (pathA: string, pathB: string) => typedError<DiffLine[], string>(__TAURI_INVOKE("diff_files", { pathA, pathB })),
	/**
	 *  Search for files and directories by name (case-insensitive matching).
	 *  Stops recursing into directories named 'node_modules', '.git', '.svn' to avoid deep scans.
	 */
	searchFiles: (query: string, basePath: string) => typedError<FileEntry[], string>(__TAURI_INVOKE("search_files", { query, basePath })),
	/**
	 *  Search file contents for a given query string.
	 *  Only searches text-like files (by extension). Returns matching lines.
	 */
	searchContent: (query: string, basePath: string) => typedError<ContentMatch[], string>(__TAURI_INVOKE("search_content", { query, basePath })),
	/**  Highlight source code and return HTML with class-based syntax spans. */
	highlightFile: (path: string) => typedError<string | null, string>(__TAURI_INVOKE("highlight_file", { path })),
	/**  Get the standard system directories (Desktop, Downloads, Documents, etc.). */
	getSystemDirs: () => typedError<FileEntry[], string>(__TAURI_INVOKE("get_system_dirs")),
	/**
	 *  Get the list of available drives on Windows (e.g. C:\, D:\).
	 *  On non-Windows systems, returns the root "/" directory.
	 */
	getDrives: () => typedError<string[], string>(__TAURI_INVOKE("get_drives")),
	/**  Get the current user's home directory path. */
	getHomeDir: () => typedError<string, string>(__TAURI_INVOKE("get_home_dir")),
	/**
	 *  Retrieve git status for files under the given directory.
	 *  Returns an empty vec if the directory is not inside a git repository.
	 */
	getGitStatus: (path: string) => typedError<GitFileStatus[], string>(__TAURI_INVOKE("get_git_status", { path })),
	/**  向 opencode CLI 发送自然语言指令并获取结果 */
	aiAsk: (prompt: string, currentDir: string) => typedError<string, string>(__TAURI_INVOKE("ai_ask", { prompt, currentDir })),
};

/* Types */
/**  A single match result from content search. */
export type ContentMatch = {
	path: string,
	line: number,
	content: string,
};

/**  A single diff operation (insertion, deletion, or unchanged line). */
export type DiffLine = {
	tag: string,
	line_a: number | null,
	line_b: number | null,
	content: string,
};

/**  Represents a file or directory entry in the file system. */
export type FileEntry = {
	/**  File name (last component of path) */
	name: string,
	/**  Absolute path of the file/directory */
	path: string,
	/**  Whether this entry is a directory */
	is_dir: boolean,
	/**  File size in bytes (0 for directories) */
	size: number,
	/**  Last modification time as ISO 8601 string */
	modified_at: string,
	/**  Creation time as ISO 8601 string */
	created_at: string,
	/**  Whether the entry is a symbolic link */
	is_symlink: boolean,
	/**  File extension in lowercase (empty for directories or no-extension files) */
	extension: string,
	/**  MIME type string (e.g. "text/plain", "image/png") */
	mime_type: string,
};

/**  Detailed file information including permissions. */
export type FileInfo = {
	/**  The basic file entry info */
	entry: FileEntry,
	/**  Unix-style permission string (e.g. "rw-r--r--") */
	permissions: string,
	/**  Whether the current user can access this file */
	accessible: boolean,
};

export type GitFileStatus = {
	path: string,
	status: string,
	staged: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

